run_time_seconds: 5

aws:
    region_name: eu-west-1

locations:
    s3_bucket: eventprocessing-part1-locationss3bucket-ne8nmobj2sgs
    s3_key: locations.json

deduplicator:
    cache_time_to_live_seconds: 300

averager:
    average_period_seconds: 60
    expiry_time_seconds: 300

receiver:
    sns_topic_arn: arn:aws:sns:eu-west-1:552908040772:EventProcessing-Part1-snsTopicSensorDataPart1-1001WZ2UL827H